### PR TITLE
Insert data to Mongo

### PR DESCRIPTION
**Pull request by rachelhongca**
created new struct for transcription data (same as Anosha's in pr #36)
wrote function to connect to database, write data

### CODE REVIEW

**Comment by rachelhongca** [comment]
there's an issue with the struct, and we can't commit the godep changes...
@anoshaminai @sandlerben

**Comment by sandlerben** [comment]
Once this is tested and working I will review the code

**Comment by yoninachmany** [comment]
@rachelhongca any progress on understanding why checks have failed? The details of Travis say it's in `make test` but don't give a lot more than that

**Comment by sandlerben** [comment]
I think the tests failing are because of withmock. I think we will switch how we do mock testing asap so don't let the failures dissuade us from merging this in.

**Pull request merged**
