### PR TITLE
Made with <3 by Hack4Impact goes off page

### PR DESCRIPTION
**Pull request by yoninachmany**
@sandlerben is this sufficient?

Page loads, no footer:
screen shot 2016-04-29 at 1 12 35 am

Scroll down, footer:
screen shot 2016-04-29 at 1 12 37 am

Refresh page, footer still there --> problem?
screen shot 2016-04-29 at 1 12 44 am

### CODE REVIEW

**Comment by sandlerben** [comment]
@yoninachmany we talked in person about what the real functionality should be

**Comment by yoninachmany** [comment]
Can you remind me of an example that does that?

**Comment by sandlerben** [comment]
I can't think of one

**Comment by yoninachmany** [comment]
That's ok - can you just remind me of the specifics?

**Comment by sandlerben** [comment]
Yeah when you first load the page, it should look like this

screen shot 2016-04-29 at 1 12 44 am

It should not be possible to scroll up or down

**Comment by yoninachmany** [comment]
@sandlerben changed css, lmk how it looks

**Comment by sandlerben** [comment]
@yoninachmany seems closer but not quite there 
image

**Comment by yoninachmany** [comment]
hacky way (below), but does it work?

```
  `body > .grid {
    height: 97%;
  }`
```

**Comment by sandlerben** [comment]
@yoninachmany turns out this is built into semantic -- see diff for details

**Pull request merged**
