### PR TITLE
Added all dependencies in a vendor directory

### PR DESCRIPTION
**Pull request by sandlerben**
See https://blog.gopheracademy.com/advent-2015/vendor-folder/ for some details

### CODE REVIEW

**Comment by sandlerben** [comment]
r @yoninachmany

**Comment by yoninachmany** [comment]
aside from that screenshot ^, lgtm

**Comment by sandlerben** [comment]
There was no reason to gitignore that directory anymore since we are vendoring dependencies now.

**Comment by sandlerben** [comment]
@yoninachmany good to merge?

**Comment by yoninachmany** [comment]
@sandlerben last thing is the `go test` comment

**Comment by sandlerben** [comment]
@yoninachmany What do you mean

> last thing is the go test comment

**Comment by yoninachmany** [comment]
last thing before merging is talking through the comment i left about `go test`

**Comment by sandlerben** [comment]
@yoninachmany ok thank you I'm going to merge

**Comment by yoninachmany** [comment]
:shipit:

**Pull request merged**
